export interface RestaurantClient {
  id: string;
  clientCode: string;
  name: string;
  dailySpend: number;
  roas: number;
  strategySummary: string;
  status: 'active' | 'paused' | 'pending';
  lastUpdated: string;
}

// Real client data from Pinecone content-brain index (93 clients)
// Last synced: 2026-02-22
export const mockClients: RestaurantClient[] = [
  { id: '1', clientCode: 'D-013', name: 'Baracoa Cuban Restaurant', dailySpend: 65.10, roas: 0, strategySummary: '2 campaigns. 86 clicks, 8 conv. CPC $0.76, CTR 1.83%. AM: Adam T.', status: 'active', lastUpdated: '1 day ago' },
  { id: '2', clientCode: 'D-124', name: 'TC Landos - 3 Locations', dailySpend: 17.94, roas: 0, strategySummary: '2 campaigns. 84 clicks, 4 conv. CTR 2.00%. AM: Paola.', status: 'active', lastUpdated: '1 day ago' },
  { id: '3', clientCode: 'D-269', name: 'Tyger Tyger', dailySpend: 52.45, roas: 0, strategySummary: '2 campaigns. 119 clicks, 5 conv. CTR 0.99%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '4', clientCode: 'D-410', name: 'DosBros Fresh Mexican Grill', dailySpend: 35.39, roas: 0, strategySummary: '2 campaigns. 46 clicks, 17 conv. CTR 1.01%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '5', clientCode: 'D-442', name: 'Handels Ice Cream - Northridge', dailySpend: 52.36, roas: 0, strategySummary: '2 campaigns. 92 clicks, 15 conv. CTR 1.27%. AM: Adam T.', status: 'active', lastUpdated: '1 day ago' },
  { id: '6', clientCode: 'D-480', name: "Lucky's Drive-In - Sacramento", dailySpend: 57.87, roas: 0, strategySummary: '2 campaigns. 136 clicks, 8 conv. CTR 1.49%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '7', clientCode: 'D-531', name: 'Torrance Tavern', dailySpend: 92.90, roas: 0, strategySummary: '2 campaigns. 120 clicks, 18 conv. CTR 1.05%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '8', clientCode: 'D-569', name: 'Tuscano Italian Kitchen', dailySpend: 5.12, roas: 0, strategySummary: '2 campaigns. 35 clicks, 3 conv. CTR 1.19%. AM: Monika O.', status: 'active', lastUpdated: '1 day ago' },
  { id: '9', clientCode: 'D-623', name: 'Screaming Goat Yard & Tap', dailySpend: 35.02, roas: 0, strategySummary: '2 campaigns. 53 clicks, 10 conv. CTR 11.16%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '10', clientCode: 'D-696', name: "Mom's Kitchen", dailySpend: 52.82, roas: 0, strategySummary: '2 campaigns. 270 clicks, 22 conv. CTR 4.01%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '11', clientCode: 'D-698', name: "Malee's Kitchen", dailySpend: 61.65, roas: 0, strategySummary: '2 campaigns. 63 clicks, 6 conv. CTR 1.13%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '12', clientCode: 'D-767', name: 'Omo Teppan & Kitchen', dailySpend: 75.60, roas: 0, strategySummary: '2 campaigns. 209 clicks, 26 conv. CTR 2.05%. AM: Adam T.', status: 'active', lastUpdated: '1 day ago' },
  { id: '13', clientCode: 'D-780', name: 'Nomade Cocina', dailySpend: 36.10, roas: 0, strategySummary: '2 campaigns. 155 clicks, 3 conv. CTR 1.82%. AM: Paola.', status: 'active', lastUpdated: '1 day ago' },
  { id: '14', clientCode: 'D-914', name: 'Hazels', dailySpend: 53.64, roas: 0, strategySummary: '2 campaigns. 82 clicks, 6 conv. CTR 2.09%. AM: Adam.', status: 'active', lastUpdated: '1 day ago' },
  { id: '15', clientCode: 'D-929', name: 'Amber Steak House', dailySpend: 40.07, roas: 0, strategySummary: '2 campaigns. 100 clicks, 0 conv. CTR 0.43%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '16', clientCode: 'D-931', name: "Smith's Boathouse Restaurant", dailySpend: 25.66, roas: 0, strategySummary: '2 campaigns. 41 clicks, 0 conv. CTR 2.21%. AM: Monika O.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '17', clientCode: 'D-994', name: 'The Gatsby', dailySpend: 14.62, roas: 0, strategySummary: '2 campaigns. 160 clicks, 0 conv. CTR 1.74%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '18', clientCode: 'D-1043', name: 'A Bite of Mexico', dailySpend: 40.82, roas: 0, strategySummary: '2 campaigns. 148 clicks, 11 conv. CTR 3.04%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '19', clientCode: 'D-1169', name: 'Original Kabob Factory', dailySpend: 128.87, roas: 0, strategySummary: '2 campaigns. 162 clicks, 0 conv. CTR 1.11%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '20', clientCode: 'D-1179', name: 'Sushi Thai', dailySpend: 85.86, roas: 0, strategySummary: '2 campaigns. 200 clicks, 13 conv. CTR 1.04%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '21', clientCode: 'D-1185', name: 'Top Shelf Sports Lounge', dailySpend: 57.60, roas: 0, strategySummary: '1 campaign. 16 clicks, 0 conv. CTR 5.86%. AM: Paola A.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '22', clientCode: 'D-1194', name: 'Cousins Pub', dailySpend: 38.48, roas: 0, strategySummary: '2 campaigns. 60 clicks, 0 conv. CTR 1.08%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '23', clientCode: 'D-1195', name: 'Public House', dailySpend: 38.18, roas: 0, strategySummary: '2 campaigns. 31 clicks, 1 conv. CTR 0.57%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '24', clientCode: 'D-1196', name: 'Fremont Bar & Grill', dailySpend: 35.86, roas: 0, strategySummary: '2 campaigns. 53 clicks, 1 conv. CTR 0.80%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '25', clientCode: 'D-1197', name: "Bandits' Bar & Grill", dailySpend: 96.37, roas: 0, strategySummary: '2 campaigns. 119 clicks, 0 conv. CTR 1.07%. AM: Adam T.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '26', clientCode: 'D-1206', name: 'Great Escape', dailySpend: 100.91, roas: 0, strategySummary: '2 campaigns. 161 clicks, 9 conv. CTR 1.42%. AM: Justin M.', status: 'active', lastUpdated: '1 day ago' },
  { id: '27', clientCode: 'D-1218', name: "Woody's Wharf", dailySpend: 51.35, roas: 0, strategySummary: '2 campaigns. 96 clicks, 3 conv. CTR 1.16%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '28', clientCode: 'D-1233', name: 'Bourgeois Pig Cafe', dailySpend: 69.87, roas: 0, strategySummary: '2 campaigns. 242 clicks, 6 conv. CTR 1.64%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '29', clientCode: 'D-1238', name: 'Rebellion Beachside Bar And Bistro', dailySpend: 35.78, roas: 0, strategySummary: '2 campaigns. 64 clicks, 0 conv. CTR 1.18%. AM: Paola A.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '30', clientCode: 'D-1242', name: 'Link & Pin - NorthCross', dailySpend: 142.22, roas: 0, strategySummary: '2 campaigns. 152 clicks, 2 conv. CTR 0.82%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '31', clientCode: 'D-1252', name: 'Tropics', dailySpend: 49.80, roas: 0, strategySummary: '2 campaigns. 37 clicks, 2 conv. CTR 1.05%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '32', clientCode: 'D-1253', name: 'Niwaala', dailySpend: 44.56, roas: 0, strategySummary: '2 campaigns. 99 clicks, 0 conv. CTR 1.18%. AM: Adam T.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '33', clientCode: 'D-1276', name: 'Bargean Miami', dailySpend: 52.83, roas: 0, strategySummary: '2 campaigns. 105 clicks, 0 conv. CTR 1.38%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '34', clientCode: 'D-1277', name: 'Brasserie Byronz', dailySpend: 90.77, roas: 0, strategySummary: '2 campaigns. 189 clicks, 0 conv. CTR 3.18%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '35', clientCode: 'D-1288', name: 'Cooked', dailySpend: 88.71, roas: 0, strategySummary: '2 campaigns. 49 clicks, 3 conv. CTR 1.29%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '36', clientCode: 'D-1290', name: "Crazy Rock'n Sushi", dailySpend: 42.86, roas: 0, strategySummary: '2 campaigns. 123 clicks, 3 conv. CTR 2.06%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '37', clientCode: 'D-1293', name: 'Tandoori Bites', dailySpend: 38.10, roas: 0, strategySummary: '2 campaigns. 116 clicks, 4 conv. CTR 1.08%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '38', clientCode: 'D-1294', name: 'LAFC', dailySpend: 170.65, roas: 0, strategySummary: '2 campaigns. 201 clicks, 5 conv. CTR 0.94%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '39', clientCode: 'D-1296', name: "Greer's", dailySpend: 90.38, roas: 0, strategySummary: '2 campaigns. 172 clicks, 2 conv. CTR 1.51%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '40', clientCode: 'D-1298', name: 'Suns Sports Bar', dailySpend: 61.13, roas: 0, strategySummary: '2 campaigns. 148 clicks, 3 conv. CTR 1.11%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '41', clientCode: 'D-1300', name: 'Canopy Road Cafe - 3 Locations', dailySpend: 103.28, roas: 0, strategySummary: '2 campaigns. 190 clicks, 3 conv. CTR 1.50%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '42', clientCode: 'D-1301', name: 'Lenas Soul Food Cafe', dailySpend: 66.54, roas: 0, strategySummary: '2 campaigns. 106 clicks, 6 conv. CTR 2.96%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '43', clientCode: 'D-1304', name: 'The Curry Up Now', dailySpend: 44.08, roas: 0, strategySummary: '2 campaigns. 84 clicks, 3 conv. CTR 2.07%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '44', clientCode: 'D-1307', name: 'The Salty Pelican', dailySpend: 36.52, roas: 0, strategySummary: '2 campaigns. 112 clicks, 6 conv. CTR 2.02%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '45', clientCode: 'D-1308', name: 'Sushi Cruise', dailySpend: 67.24, roas: 0, strategySummary: '2 campaigns. 167 clicks, 10 conv. CTR 2.47%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '46', clientCode: 'D-1313', name: 'Tikkaway Grill', dailySpend: 63.45, roas: 0, strategySummary: '2 campaigns. 152 clicks, 7 conv. CTR 1.71%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '47', clientCode: 'D-1318', name: 'Shiso Sushi', dailySpend: 17.82, roas: 0, strategySummary: '2 campaigns. 60 clicks, 8 conv. CTR 2.68%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '48', clientCode: 'D-1320', name: 'La Mina', dailySpend: 53.35, roas: 0, strategySummary: '2 campaigns. 91 clicks, 5 conv. CTR 1.16%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '49', clientCode: 'D-1322', name: 'Birch & Vine', dailySpend: 35.96, roas: 0, strategySummary: '2 campaigns. 50 clicks, 0 conv. CTR 0.94%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '50', clientCode: 'D-1324', name: 'Toasted Yolk Cafe - Victoria', dailySpend: 58.23, roas: 0, strategySummary: '2 campaigns. 40 clicks, 2 conv. CTR 0.42%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '51', clientCode: 'D-1326', name: 'Foxy Sushi', dailySpend: 35.90, roas: 0, strategySummary: '2 campaigns. 52 clicks, 4 conv. CTR 1.01%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '52', clientCode: 'D-1327', name: 'El Burro Loco', dailySpend: 39.68, roas: 0, strategySummary: '2 campaigns. 221 clicks, 8 conv. CTR 2.68%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '53', clientCode: 'D-1329', name: 'Barrel 33', dailySpend: 37.68, roas: 0, strategySummary: '2 campaigns. 90 clicks, 0 conv. CTR 0.51%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '54', clientCode: 'D-1337', name: 'Corridor', dailySpend: 59.79, roas: 0, strategySummary: '2 campaigns. 168 clicks, 6 conv. CTR 3.26%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '55', clientCode: 'D-1339', name: 'Wild Thyme Kitchen & Cocktails', dailySpend: 152.60, roas: 0, strategySummary: '2 campaigns. 323 clicks, 3 conv. CTR 1.43%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '56', clientCode: 'D-1341', name: 'Bake & Brew', dailySpend: 44.30, roas: 0, strategySummary: '2 campaigns. 122 clicks, 6 conv. CTR 1.22%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '57', clientCode: 'D-1343', name: "Moe's Southwest Grill", dailySpend: 24.96, roas: 0, strategySummary: '2 campaigns. 128 clicks, 3 conv. CTR 1.03%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '58', clientCode: 'D-1345', name: 'Park Social', dailySpend: 58.04, roas: 0, strategySummary: '2 campaigns. 114 clicks, 2 conv. CTR 0.26%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '59', clientCode: 'D-1348', name: 'Kojin', dailySpend: 16.96, roas: 0, strategySummary: '2 campaigns. 24 clicks, 0 conv. CTR 0.39%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '60', clientCode: 'D-1350', name: "The Loft at Duckworth's", dailySpend: 35.90, roas: 0, strategySummary: '2 campaigns. 60 clicks, 3 conv. CTR 0.97%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '61', clientCode: 'D-1352', name: 'Armor Coffee', dailySpend: 40.30, roas: 0, strategySummary: '2 campaigns. 72 clicks, 9 conv. CTR 1.22%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '62', clientCode: 'D-1353', name: 'Gyuzo Japanese BBQ', dailySpend: 37.63, roas: 0, strategySummary: '2 campaigns. 273 clicks, 12 conv. CTR 3.97%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '63', clientCode: 'D-1355', name: 'Jackson Ventures IPOT', dailySpend: 59.64, roas: 0, strategySummary: '2 campaigns. 378 clicks, 3 conv. CTR 1.20%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '64', clientCode: 'D-1357', name: 'Rocket Dogs', dailySpend: 60.94, roas: 0, strategySummary: '2 campaigns. 237 clicks, 14 conv. CTR 1.42%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '65', clientCode: 'D-1361', name: 'Churasuko', dailySpend: 63.34, roas: 0, strategySummary: '2 campaigns. 306 clicks, 6 conv. CTR 1.50%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '66', clientCode: 'D-1369', name: 'Maha Juice Bar - Norwood', dailySpend: 13.96, roas: 0, strategySummary: '2 campaigns. 11 clicks, 1 conv. CTR 33.33%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '67', clientCode: 'D-1371', name: 'Grill Marx - Town Center', dailySpend: 415.99, roas: 0, strategySummary: '2 campaigns. 1094 clicks, 5 conv. CTR 2.29%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '68', clientCode: 'D-1372', name: 'Pistacchio Pane e Caffe', dailySpend: 37.40, roas: 0, strategySummary: '2 campaigns. 195 clicks, 7 conv. CTR 1.16%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '69', clientCode: 'D-1374', name: 'Green Dirt Farm On Oak', dailySpend: 35.51, roas: 0, strategySummary: '2 campaigns. 162 clicks, 3 conv. CTR 1.06%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '70', clientCode: 'D-1375', name: "RuRu's Tacos & Tequila", dailySpend: 36.80, roas: 0, strategySummary: '2 campaigns. 139 clicks, 9 conv. CTR 2.30%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '71', clientCode: 'D-1376', name: 'Tabboulee - Gyros & Falafels', dailySpend: 33.40, roas: 0, strategySummary: '2 campaigns. 80 clicks, 5 conv. CTR 1.09%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '72', clientCode: 'D-1377', name: 'Cottonwood Creek Brewery', dailySpend: 38.57, roas: 0, strategySummary: '2 campaigns. 66 clicks, 0 conv. CTR 1.44%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '73', clientCode: 'D-1385', name: 'Stella', dailySpend: 28.79, roas: 0, strategySummary: '2 campaigns. 77 clicks, 3 conv. CTR 1.42%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '74', clientCode: 'D-1386', name: "Big Jim's Famous Steaks", dailySpend: 65.75, roas: 0, strategySummary: '2 campaigns. 136 clicks, 3 conv. CTR 1.18%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '75', clientCode: 'D-1387', name: 'Finca', dailySpend: 46.66, roas: 0, strategySummary: '2 campaigns. 142 clicks, 1 conv. CTR 1.26%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '76', clientCode: 'D-1389', name: 'Vintage Books', dailySpend: 32.76, roas: 0, strategySummary: '2 campaigns. 116 clicks, 3 conv. CTR 1.54%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '77', clientCode: 'D-1390', name: "Tiki's Grill & Bar", dailySpend: 39.11, roas: 0, strategySummary: '2 campaigns. 425 clicks, 1 conv. CTR 1.81%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '78', clientCode: 'D-1391', name: 'Prime Social Kitchen', dailySpend: 37.48, roas: 0, strategySummary: '2 campaigns. 25 clicks, 0 conv. CTR 0.30%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '79', clientCode: 'D-1393', name: 'Tacos Tu Madre', dailySpend: 46.50, roas: 0, strategySummary: '2 campaigns. 101 clicks, 2 conv. CTR 1.64%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '80', clientCode: 'D-1394', name: 'Sway', dailySpend: 39.43, roas: 0, strategySummary: '2 campaigns. 45 clicks, 7 conv. CTR 0.75%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '81', clientCode: 'D-1395', name: 'Moxies Grill & Bar', dailySpend: 22.47, roas: 0, strategySummary: '2 campaigns. 71 clicks, 6 conv. CTR 2.45%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '82', clientCode: 'D-1396', name: 'Greenleaf Chopshop', dailySpend: 70.29, roas: 0, strategySummary: '2 campaigns. 161 clicks, 5 conv. CTR 2.45%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '83', clientCode: 'D-1397', name: 'Beerhaus', dailySpend: 128.60, roas: 0, strategySummary: '2 campaigns. 281 clicks, 3 conv. CTR 1.27%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '84', clientCode: 'D-1398', name: "Peggy's", dailySpend: 14.91, roas: 0, strategySummary: '2 campaigns. 98 clicks, 0 conv. CTR 2.47%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '85', clientCode: 'D-1399', name: 'El Patio and Bar Habana', dailySpend: 238.70, roas: 0, strategySummary: '2 campaigns. 524 clicks, 3 conv. CTR 0.93%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '86', clientCode: 'D-1400', name: 'Humo Mexican Kitchen', dailySpend: 36.05, roas: 0, strategySummary: '2 campaigns. 37 clicks, 4 conv. CTR 0.62%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '87', clientCode: 'D-1401', name: 'Jajaja Mexicana', dailySpend: 80.47, roas: 0, strategySummary: '2 campaigns. 204 clicks, 0 conv. CTR 1.60%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '88', clientCode: 'D-1402', name: 'Ramen Shack', dailySpend: 38.02, roas: 0, strategySummary: '2 campaigns. 83 clicks, 6 conv. CTR 1.09%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '89', clientCode: 'D-1403', name: 'The Montrose', dailySpend: 23.21, roas: 0, strategySummary: '2 campaigns. 44 clicks, 0 conv. CTR 0.81%.', status: 'pending', lastUpdated: '1 day ago' },
  { id: '90', clientCode: 'D-1413', name: 'Little Hen - Houston', dailySpend: 246.06, roas: 0, strategySummary: '2 campaigns. 542 clicks, 11 conv. CTR 0.81%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '91', clientCode: 'D-1416', name: 'Deluxe Fun Dining', dailySpend: 144.29, roas: 0, strategySummary: '2 campaigns. 257 clicks, 16 conv. CTR 1.19%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '92', clientCode: 'D-1417', name: 'Sea Grill', dailySpend: 129.93, roas: 0, strategySummary: '2 campaigns. 286 clicks, 11 conv. CTR 1.33%.', status: 'active', lastUpdated: '1 day ago' },
  { id: '93', clientCode: 'D-1418', name: 'Cha Cha Chicken', dailySpend: 91.64, roas: 0, strategySummary: '2 campaigns. 271 clicks, 2 conv. CTR 0.99%.', status: 'active', lastUpdated: '1 day ago' },
];
